export const WEDDING = {
  envelope: "envelope-cover",
  envelopeFlap: "envelope-flap",
  envelopeOpen: "envelope-open",
  letterContent: "letter-content",
  coupleSection: "couple-section",
  messageSection: "message-section",
  scratchCanvas: "scratch-canvas",
  scratchCard: "scratch-card",
  dateReveal: "date-reveal",
  countdown: "countdown-timer",
  countdownDays: "countdown-days",
  countdownHours: "countdown-hours",
  countdownMinutes: "countdown-minutes",
  countdownSeconds: "countdown-seconds",
  venueSection: "venue-section",
  mapButton: "map-button",
  bgmToggle: "bgm-toggle",
  shareWhatsapp: "share-whatsapp",
  shareCopy: "share-copy",
  scrollIndicator: "scroll-indicator",
};
